version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
    command:
      bash -c "rake db:migrate && rake db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"

  redis:
    image: redis:5.0.10-alpine
